<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="1" failed="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="37301" started-at="2017-07-30T04:22:33Z" finished-at="2017-07-30T04:23:10Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="37301" started-at="2017-07-30T04:22:33Z" finished-at="2017-07-30T04:23:10Z">
      <class name="testCases.VerifyHomePage">
        <test-method status="FAIL" signature="setUp()[pri:0, instance:testCases.VerifyHomePage@d8355a8]" name="setUp" is-config="true" duration-ms="0" started-at="2017-07-30T09:52:33Z" finished-at="2017-07-30T09:52:33Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at dataProvider.ConfigDataProvider.getApplicationUrl(ConfigDataProvider.java:37)
	at testCases.VerifyHomePage.setUp(VerifyHomePage.java:24)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:564)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:653)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="SKIP" signature="testHomePage()[pri:0, instance:testCases.VerifyHomePage@d8355a8]" name="testHomePage" duration-ms="4" started-at="2017-07-30T09:53:10Z" finished-at="2017-07-30T09:53:10Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testHomePage -->
        <test-method status="SKIP" signature="tearDown()[pri:0, instance:testCases.VerifyHomePage@d8355a8]" name="tearDown" is-config="true" duration-ms="0" started-at="2017-07-30T09:53:10Z" finished-at="2017-07-30T09:53:10Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- testCases.VerifyHomePage -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
